name: Build and Deploy

on:
  workflow_dispatch:

env:
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Packer Init
        working-directory: ./packer
        run: packer init .

      - name: Packer Build
        working-directory: ./packer
        run: packer build .

      - name: Get HCP Packer Iteration ID from Packer Manifest
        id: hcp
        working-directory: ./packer
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          iteration_id=$(echo "$build" | jq -r '.custom_data.iteration_id')
          echo "::set-output name=iteration_id::$iteration_id"

  test:
    name: E2E Testing
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Perform Tests
        run: echo "E2E Testing Completed"

  promote-dev-staging:
    name: Promote to Dev and Staging Channels
    needs: ['build', 'test'] # this will automatically be skipped if the test job fails
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Promote Iteration to Dev
        working-directory: .github/scripts
        run: ./set_iteration.sh "hcp-packer-demo" "dev" "${{ needs.build.outputs.iteration_id }}"

      - name: Promote Iteration to Staging
        working-directory: .github/scripts
        run: ./set_iteration.sh "hcp-packer-demo" "staging" "${{ needs.build.outputs.iteration_id }}"

  promote-prod:
    name: Promote to Production
    needs: ['build', 'test', 'promote-dev-staging']
    environment: production # requires approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Promote Iteration to Prod
        working-directory: .github/scripts
        run: ./set_iteration.sh "hcp-packer-demo" "prod" "${{ needs.build.outputs.iteration_id }}"