name: Build and Deploy

on:
  workflow_dispatch:

env:
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Packer Init
        run: packer init .

      - name: Packer Build
        run: packer build .

  test:
    name: E2E Testing
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Perform Tests
        run: echo "E2E Testing Completed"